### ISSUE TITLE
Failed to initialize IOMMU.

### ISSUE THREAD

**Issue by bdogrulz** [ra1nstorm/ra1nstorm-helper#45] opened 2019-11-26 07:38 UTC
so everything is done i can boot into the vm on the first time just fine but when it needs to pass-though the device and i have to reboot that is where everything goes wrong when i select boot VM in the ra1nstorm.run i get this "Failed to initialize IOMMU. Please make sure IOMMU (or VT-d) is enabled in the advanced settings in your BIOS" error but secure boot is disabled and my BIOS has the VMM feature enabled. device is an iPhone 8 ios 13.1.3 connected directly to my laptop
[SystemLog.txt](https://github.com/ra1nstorm/ra1nstorm-helper/files/3890558/SystemLog.txt)

**Comment by karyeet** [comment] 2019-11-26 07:44
Duplicate of #43

**Comment by or99** [comment] 2019-11-26 12:25
Same thing for me! 
It’s enabled on my bios and it says the same thing

**Closed as completed** 2019-11-26 17:23 UTC
Labels: bug, duplicate
